builds:
  id: "virtualslime"
  main: "./src"
  goos:
    - freebsd
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
    - goos: darwin
      goarch: arm
    - goos: freebsd
      goarch: arm64
