version: "3.5"
services:
  rawserver:
    build:
      context: .
      network: host
    ports:
      - 3000:3000
    environment:
      - APP_ENV=production
      - PORT=3000
      - DOMAIN=v-sli.me
      - DEBUG=false
    restart: always
